<?php

declare(strict_types=1);

return [
    [
        'name' => 'API - Health',
        'type' => 'http',
        'method' => 'GET',
        'path' => '/api/v1/health',
        'auth' => false,
        'expected' => 'HTTP 200, success=true.',
        'assertions' => ['http_200', 'success_true'],
    ],
    [
        'name' => 'AUTH - Login QA',
        'type' => 'login',
        'expected' => 'Login correcto y token disponible si TEST_AUTH_EMAIL/TEST_AUTH_PASSWORD estan configurados.',
        'assertions' => ['http_200', 'success_true', 'token_present'],
    ],
    [
        'name' => 'GOOGLE OAUTH - Status',
        'type' => 'http',
        'method' => 'GET',
        'path' => '/api/v1/integrations/google/status',
        'auth' => true,
        'expected' => 'HTTP 200, success=true, estado calendar/gmail disponible.',
        'assertions' => ['http_200', 'success_true'],
    ],
    [
        'name' => 'GOOGLE OAUTH - Auth URL Calendar',
        'type' => 'http',
        'method' => 'GET',
        'path' => '/api/v1/integrations/google/auth-url?service=calendar',
        'auth' => true,
        'expected' => 'Genera URL con calendar.events, access_type=offline y prompt=consent.',
        'assertions' => ['http_200', 'success_true', 'auth_url_present', 'auth_url_calendar_scope', 'auth_url_offline', 'auth_url_prompt_consent'],
    ],
    [
        'name' => 'GOOGLE OAUTH - Auth URL Gmail',
        'type' => 'http',
        'method' => 'GET',
        'path' => '/api/v1/integrations/google/auth-url?service=gmail',
        'auth' => true,
        'expected' => 'Genera URL con gmail.send, access_type=offline y prompt=consent.',
        'assertions' => ['http_200', 'success_true', 'auth_url_present', 'auth_url_gmail_scope', 'auth_url_offline', 'auth_url_prompt_consent'],
    ],
    [
        'name' => 'GOOGLE OAUTH - Auth URL Both',
        'type' => 'http',
        'method' => 'GET',
        'path' => '/api/v1/integrations/google/auth-url?service=both',
        'auth' => true,
        'expected' => 'Genera URL con scopes de Calendar y Gmail.',
        'assertions' => ['http_200', 'success_true', 'auth_url_calendar_scope', 'auth_url_gmail_scope'],
    ],
    [
        'name' => 'GOOGLE OAUTH - Servicio invalido',
        'type' => 'http',
        'method' => 'GET',
        'path' => '/api/v1/integrations/google/auth-url?service=drive',
        'auth' => true,
        'expected' => 'HTTP 422 VALIDATION_ERROR.',
        'assertions' => ['http_422', 'success_false'],
    ],
    [
        'name' => 'GOOGLE OAUTH - Disconnect local',
        'type' => 'http',
        'method' => 'POST',
        'path' => '/api/v1/integrations/google/disconnect',
        'auth' => true,
        'expected' => 'Revocacion local, sin llamada real a Google.',
        'assertions' => ['http_200', 'success_true'],
    ],
    [
        'name' => 'GOOGLE CALENDAR STUB - Cuenta placeholder',
        'type' => 'calendar_placeholder',
        'expected' => 'Crea calendar_accounts activo con provider google y auditoria.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'GOOGLE CALENDAR STUB - Crear reunion y evento',
        'type' => 'calendar_meeting',
        'expected' => 'Crea agenda_item meeting y calendar_events synced con external_event_id stub-gcal.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'GOOGLE CALENDAR STUB - Cancelar evento',
        'type' => 'calendar_cancel',
        'expected' => 'Marca calendar_events como cancelled.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'EMAIL STUB - Envio directo simulado',
        'type' => 'email_stub_direct',
        'expected' => 'EmailSenderStub devuelve success=true, simulated=true y external_message_id.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'EMAIL STUB - Notificacion futura programada',
        'type' => 'email_notification_future',
        'expected' => 'Crea agenda_notification email scheduled/pending, no envia aun.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'EMAIL STUB - Notificacion vencida confirmada',
        'type' => 'email_notification_due',
        'expected' => 'Crea agenda_notification email y la marca sent por stub.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'WHATSAPP STUB - Telefono externo E.164',
        'type' => 'whatsapp_notification_future',
        'expected' => 'Permite telefono externo E.164 y deja scheduled/pending.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'WHATSAPP STUB - Telefono invalido bloqueado',
        'type' => 'whatsapp_invalid_phone',
        'expected' => 'Bloquea telefono no E.164 con AGENDA_INVALID_E164_PHONE.',
        'assertions' => ['direct_success'],
    ],
    [
        'name' => 'AUDIO STUB - WhatsApp interno audio',
        'type' => 'whatsapp_audio_http',
        'expected' => 'message.php responde response_mode=audio si TEST_WHATSAPP_PHONE esta configurado.',
        'assertions' => ['http_200', 'success_true', 'response_mode_audio'],
    ],
];
